title: Puteradarma Sulaiman
description: Data Consultant and Solutions Architect
site_title: '@puteradarmas - Puteradarma Sulaiman'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: puteradarmas
email: puteradarmas19@gmailcom.com

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 
